const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, LevelFormat, PageBreak, BorderStyle
  } = require('docx');
  const fs = require('fs');
  
  const BLUE = "1F3864";
  const DARKBLUE = "2E5496";
  const GRAY = "F2F2F2";
  
  function heading1(text) {
    return new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      children: [new TextRun({ text, bold: true, size: 28, color: BLUE, font: "Arial" })]
    });
  }
  
  function heading2(text) {
    return new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text, bold: true, size: 24, color: DARKBLUE, font: "Arial" })]
    });
  }
  
  function body(text) {
    return new Paragraph({
      spacing: { after: 120, line: 320 },
      children: [new TextRun({ text, size: 22, font: "Arial" })]
    });
  }
  
  function code(text) {
    return new Paragraph({
      spacing: { after: 100, before: 100 },
      indent: { left: 720 },
      children: [new TextRun({ text, size: 18, font: "Courier New", color: "333333" })],
      border: { left: { style: BorderStyle.SINGLE, size: 6, color: "AAAAAA", space: 10 } }
    });
  }
  
  function bullet(text, bold_part) {
    return new Paragraph({
      numbering: { reference: "bullets", level: 0 },
      spacing: { after: 80 },
      children: bold_part
        ? [new TextRun({ text: bold_part, bold: true, size: 22, font: "Arial" }),
           new TextRun({ text: " " + text, size: 22, font: "Arial" })]
        : [new TextRun({ text, size: 22, font: "Arial" })]
    });
  }
  
  function empty() {
    return new Paragraph({ children: [new TextRun("")], spacing: { after: 80 } });
  }
  
  const questions = [
    {
      id: 1,
      title: "Питання 1. Поняття паралельних, псевдопаралельних та розподілених обчислень",
      content: [
        heading2("Загальний контекст"),
        body("Сучасні обчислювальні системи використовують три принципово різні підходи до виконання задач: паралельні, псевдопаралельні та розподілені обчислення. Кожен підхід має своє місце у курсі технологій паралельних обчислень і підкріплюється практичними прикладами на Java та MPI."),
        empty(),
        heading2("Паралельні обчислення"),
        body("Паралельні обчислення — це одночасне виконання кількох задач або операцій на кількох фізичних обчислювальних одиницях (ядрах процесора). Фізично різні ядра одночасно обробляють різні частини задачі. Наприклад, стрічковий алгоритм множення матриць розподіляє рядки між потоками, і кожне ядро реально одночасно обчислює свою частину добутку."),
        body("У Java паралелізм реалізується через Thread, Runnable, ExecutorService (FixedThreadPool, ForkJoinPool). При множенні матриць N×N кожен потік отримує block рядків і обчислює їх незалежно — це справжній паралелізм, якщо є достатньо ядер."),
        empty(),
        heading2("Псевдопаралельні обчислення"),
        body("Псевдопаралельні обчислення — це ілюзія одночасності на одному фізичному ядрі. Операційна система швидко перемикає контекст між потоками (time-slicing), завдяки чому здається, що вони виконуються одночасно. Важливо: в моменти вводу-виводу (I/O) потік звільняє ядро, і воно може виконувати іншу задачу."),
        body("Приклад з курсу: імітація системи масового обслуговування (СМО) на FixedThreadPool. На одноядерній машині потоки виконуються псевдопаралельно, але для задач з очікуванням (клієнт 'обслуговується' з паузою Thread.sleep) це ефективно, оскільки потоки блокуються і не витрачають CPU."),
        empty(),
        heading2("Розподілені обчислення"),
        body("Розподілені обчислення — це виконання задачі на кількох окремих вузлах мережі, кожен з яких має власну пам'ять. Вузли не мають спільного адресного простору і взаємодіють через обмін повідомленнями (MPI, HTTP, сокети). Це дозволяє масштабуватись до тисяч вузлів."),
        body("У курсі: алгоритм Кеннона (Фокса) для MPI — кожен процес зберігає блок матриці у своїй пам'яті, обменюється блоками через MPI_Sendrecv або MPI_Bcast, виконує локальне множення. Spring Boot застосунок також є прикладом розподіленої системи, де клієнти надсилають запити на обчислення матриць."),
        empty(),
        heading2("Порівняльна таблиця"),
        bullet("Спільна пам'ять, одна машина, справжній паралелізм → Thread/ForkJoinPool в Java", "Паралельні:"),
        bullet("Одне ядро, перемикання контексту, ілюзія паралелізму → ефективно для I/O-bound задач", "Псевдопаралельні:"),
        bullet("Різні машини, власна пам'ять, мережевий обмін → MPI, REST, черги повідомлень", "Розподілені:"),
      ]
    },
    {
      id: 3,
      title: "Питання 3. Способи розпаралелювання",
      content: [
        heading2("Загальний контекст"),
        body("Розпаралелювання — це процес перетворення послідовної задачі на набір паралельних підзадач. Протягом курсу ми розглядали кілька підходів, кожен з яких застосовувався на конкретних прикладах: матричне множення, пошук у файлах, імітація СМО, сортування."),
        empty(),
        heading2("1. Декомпозиція за даними (Data Parallelism)"),
        body("Дані діляться між потоками/процесами, кожен обробляє свою частину. Найпоширеніший підхід при роботі з масивами та матрицями."),
        body("Приклад: стрічковий алгоритм множення матриць. Рядки матриці A розподіляються між потоками (кожен отримує block рядків). Матриця B — спільний ресурс для читання (без синхронізації, бо тільки read). Кожен потік незалежно обчислює свої рядки результату C."),
        code("int blockSize = N / numThreads;"),
        code("pool.submit(() -> {"),
        code("    for (int i = start; i < end; i++)"),
        code("        for (int j = 0; j < N; j++)"),
        code("            for (int k = 0; k < N; k++)"),
        code("                C[i][j] += A[i][k] * B[k][j];"),
        code("});"),
        empty(),
        heading2("2. Декомпозиція за задачами (Task Parallelism)"),
        body("Різні потоки виконують різні, відносно незалежні задачі. Застосовувалось при пошуку слів у наборі файлів через ForkJoinPool."),
        body("Список файлів рекурсивно ділиться на підгрупи. Кожен RecursiveTask отримує групу файлів, відкриває їх, шукає слово, повертає кількість входжень. Результати об'єднуються через join()."),
        code("class SearchTask extends RecursiveTask<Long> {"),
        code("    protected Long compute() {"),
        code("        if (files.size() <= THRESHOLD) return searchInFiles(files);"),
        code("        var left = new SearchTask(files.subList(0, mid));"),
        code("        var right = new SearchTask(files.subList(mid, files.size()));"),
        code("        left.fork();"),
        code("        return right.compute() + left.join();"),
        code("    }"),
        code("}"),
        empty(),
        heading2("3. Конвеєрний паралелізм (Producer-Consumer)"),
        body("Обробка даних проходить через ланцюжок стадій, кожна — окремий потік або група потоків. Реалізується через BlockingQueue між стадіями."),
        body("Producer генерує дані або запити (наприклад, клієнти СМО), Consumer обробляє. BlockingQueue виступає буфером: put() блокується при переповненні, take() — при порожній черзі. Це забезпечує природне backpressure."),
        empty(),
        heading2("4. Рекурсивне ділення (Divide and Conquer)"),
        body("Задача рекурсивно ділиться до базового випадку (threshold). ForkJoinPool з work-stealing забезпечує ефективний розподіл. Приклад: паралельне сортування (Arrays.parallelSort()) або пошук у файлах."),
        empty(),
        heading2("5. Алгоритмічне розпаралелювання для розподілених систем"),
        body("Спеціальні алгоритми мінімізують комунікацію: алгоритм Кеннона / Фокса (блочне множення матриць у MPI). Кожен MPI-процес зберігає блок матриці, виконує обмін лише з сусідніми процесами у 2D-решітці — мінімальна кількість повідомлень при максимальному паралелізмі."),
        empty(),
        heading2("Вибір підходу"),
        bullet("Однорідні дані великого обсягу → Data Parallelism (стрічковий алгоритм)", ""),
        bullet("Незалежні задачі різного розміру → Task Parallelism + ForkJoin (work-stealing)", ""),
        bullet("Потоковий ввід-вивід → Pipeline / Producer-Consumer", ""),
        bullet("Розподілена система → алгоритми з мінімальною комунікацією (Кеннон, Фокс)", ""),
      ]
    },
    {
      id: 5,
      title: "Питання 5. Способи підвищення продуктивності комп'ютерів. Суперкомп'ютери",
      content: [
        heading2("Загальний контекст"),
        body("Питання продуктивності є фундаментальним для паралельних обчислень. Саме обмеження однопроцесорної продуктивності (теплові обмеження, межа тактової частоти) призвели до домінування багатоядерних та розподілених систем."),
        empty(),
        heading2("1. Апаратні способи"),
        bullet("Підвищення тактової частоти — обмежено тепловиділенням (~3-5 GHz стеля)", ""),
        bullet("Багатоядерні процесори — 4, 8, 16, 64+ ядра на чіпі. Саме це зробило паралельне програмування необхідністю", ""),
        bullet("Векторні інструкції (SIMD) — SSE, AVX, AVX-512: одна інструкція обробляє вектор значень одночасно", ""),
        bullet("Ієрархія кешу L1/L2/L3 — зменшення латентності доступу до пам'яті. Cache-friendly алгоритми (стрічковий vs блочний) суттєво впливають на продуктивність", ""),
        bullet("GPU — тисячі простих ядер для масово-паралельних задач (CUDA, OpenCL)", ""),
        empty(),
        heading2("2. Архітектурні рішення"),
        bullet("Суперскалярність — виконання кількох інструкцій за один такт (out-of-order execution)", ""),
        bullet("Конвеєризація — поділ інструкції на стадії, одночасне виконання різних стадій різних інструкцій", ""),
        bullet("NUMA (Non-Uniform Memory Access) — різна латентність пам'яті залежно від вузла. У Java: впливає на ThreadLocal та розміщення об'єктів у heap", ""),
        bullet("Hyper-Threading (Intel SMT) — два логічних потоки на одному фізичному ядрі", ""),
        empty(),
        heading2("3. Програмні способи"),
        body("Алгоритмічна оптимізація дає найбільший приріст: O(n²) → O(n log n). Паралельне програмування через Java Thread, ForkJoinPool, ExecutorService. Cache-friendly доступ (рядковий обхід матриці замість стовпцевого). Lock-free структури даних (AtomicInteger, ConcurrentHashMap) замість synchronized."),
        empty(),
        heading2("Суперкомп'ютери"),
        body("Суперкомп'ютери — обчислювальні системи на десятки й сотні тисяч вузлів, з'єднаних швидкісними мережами (InfiniBand, Omni-Path). Продуктивність вимірюється у FLOPS (floating point operations per second): петафлопс = 10^15 операцій/сек."),
        bullet("Frontier (США, 2022) — перший екзафлопсний комп'ютер (10^18 FLOPS), AMD CPU + GPU", ""),
        bullet("Summit (США, IBM Power9 + NVIDIA V100) — використовується для ядерного моделювання, медицини", ""),
        bullet("WLCG (Worldwide LHC Computing Grid) — розподілена система для обробки даних LHC CERN", ""),
        body("Програмне забезпечення суперкомп'ютерів: MPI для міжвузлової комунікації, OpenMP для багатоядерного паралелізму всередині вузла (гібридна модель MPI+OpenMP). Саме стандарт MPI, що ми вивчали, є мовою суперкомп'ютерів."),
        body("Зв'язок з законом Амдала: навіть 1% послідовного коду обмежує прискорення до 100x незалежно від кількості вузлів суперкомп'ютера. Тому оптимізація послідовних ділянок критична."),
      ]
    },
    {
      id: 7,
      title: "Питання 7. Поняття потоку обчислень. Створення та запуск потоків в Java",
      content: [
        heading2("Поняття потоку"),
        body("Потік обчислень (thread) — це найменша одиниця виконання в рамках процесу. Процес може мати кілька потоків, що поділяють спільну пам'ять (heap), але кожен має власний стек виклику, лічильник команд (PC) і набір регістрів. JVM відображає Java-потоки на нативні потоки ОС."),
        body("Потоки — основа паралелізму з розділеною пам'яттю. Саме через потоки реалізуються: стрічковий алгоритм матриці, пул FixedThreadPool для СМО, пошук у файлах через ForkJoinPool."),
        empty(),
        heading2("Спосіб 1: успадкування Thread"),
        code("class MatrixWorker extends Thread {"),
        code("    private final int startRow, endRow;"),
        code("    MatrixWorker(int start, int end) { this.startRow = start; this.endRow = end; }"),
        code("    @Override public void run() {"),
        code("        for (int i = startRow; i < endRow; i++)"),
        code("            // обчислення рядка i матриці C"),
        code("    }"),
        code("}"),
        code("new MatrixWorker(0, N/2).start(); // запуск нового потоку ОС"),
        body("Важливо: виклик start() запускає новий потік і повертає негайно. Виклик run() напряму — просто виклик методу в поточному потоці, без паралелізму."),
        empty(),
        heading2("Спосіб 2: реалізація Runnable (рекомендований)"),
        code("Runnable task = () -> {"),
        code("    // лямбда-вираз як потокова задача"),
        code("    System.out.println(Thread.currentThread().getName());"),
        code("};"),
        code("Thread t = new Thread(task, \"Worker-1\");"),
        code("t.start();"),
        body("Перевага: клас може успадковувати іншу батьківську класу. Більш гнучкий підхід, використовується з ExecutorService."),
        empty(),
        heading2("Спосіб 3: Callable та Future"),
        code("ExecutorService pool = Executors.newFixedThreadPool(4);"),
        code("Future<Long> future = pool.submit(() -> {"),
        code("    return searchWord(files); // повертає результат"),
        code("});"),
        code("Long result = future.get(); // блокуючий виклик"),
        body("Callable, на відміну від Runnable, може повертати результат і кидати checked-виключення. Future.get() блокує поточний потік до отримання результату. Використовувалося при пошуку у файлах через ForkJoinPool."),
        empty(),
        heading2("Спосіб 4: ForkJoinPool і RecursiveTask"),
        body("Спеціалізований пул для рекурсивних задач. RecursiveTask<V> — задача з результатом, RecursiveAction — без. fork() відправляє підзадачу в чергу пулу, join() чекає результату."),
        empty(),
        heading2("Цикл життя потоку"),
        bullet("NEW — створений, start() ще не викликаний", ""),
        bullet("RUNNABLE — виконується або готовий до виконання (планувальник вирішує)", ""),
        bullet("BLOCKED — чекає на монітор (synchronized)", ""),
        bullet("WAITING — wait() або join() без таймауту", ""),
        bullet("TIMED_WAITING — sleep(n), wait(n), join(n)", ""),
        bullet("TERMINATED — run() завершився або виняток", ""),
      ]
    },
    {
      id: 9,
      title: "Питання 9. Клас Thread",
      content: [
        heading2("Загальний контекст"),
        body("Клас Thread є фундаментальним у Java для роботи з потоками. Хоча на практиці рекомендується використовувати вищий рівень абстракції (ExecutorService, ForkJoinPool), знання Thread є необхідним, оскільки всі ці абстракції базуються на ньому."),
        empty(),
        heading2("Ключові методи"),
        bullet("start() — ініціює новий потік ОС і викликає run() у ньому. Не блокує.", ""),
        bullet("run() — тіло потоку. Перевизначається або задається через Runnable.", ""),
        bullet("join() / join(ms) — поточний потік чекає завершення іншого. Використовується для збору результатів паралельних обчислень.", ""),
        bullet("sleep(ms) — призупинення поточного потоку. Throws InterruptedException.", ""),
        bullet("interrupt() — встановлює прапорець переривання потоку.", ""),
        bullet("isInterrupted() / Thread.interrupted() — перевірка прапорця (другий — і скидає його).", ""),
        bullet("getName() / setName() — ім'я для діагностики та логування.", ""),
        bullet("getState() — повертає Thread.State (NEW, RUNNABLE, BLOCKED, WAITING, ...).", ""),
        empty(),
        heading2("Пріоритети потоків"),
        body("Thread.setPriority(int priority) — від MIN_PRIORITY (1) до MAX_PRIORITY (10), NORM_PRIORITY (5) — дефолт. Пріоритет є підказкою планувальнику ОС, не гарантією порядку виконання. На різних ОС поводиться по-різному."),
        code("Thread worker = new Thread(() -> compute());"),
        code("worker.setPriority(Thread.MAX_PRIORITY); // підвищений пріоритет"),
        code("worker.setDaemon(false); // non-daemon (дефолт)"),
        code("worker.start();"),
        code("worker.join(); // чекаємо завершення"),
        empty(),
        heading2("Daemon-потоки"),
        body("Daemon-потоки — фонові потоки, що завершуються автоматично, коли всі non-daemon потоки завершились. JVM не чекає завершення daemon-потоків при shutdown."),
        code("Thread bg = new Thread(() -> monitor()); // фоновий моніторинг"),
        code("bg.setDaemon(true); // ОБОВ'ЯЗКОВО перед start()"),
        code("bg.start();"),
        body("Приклад використання: потік збору статистики СМО у фоні. При завершенні основного застосунку daemon-потік теж завершується. Не підходить для задач, що потребують гарантованого завершення (запис у файл тощо)."),
        empty(),
        heading2("ThreadLocal"),
        body("ThreadLocal<T> — кожен потік має власну копію змінної. Немає синхронізації, немає конкуренції."),
        code("ThreadLocal<SimpleDateFormat> formatter ="),
        code("    ThreadLocal.withInitial(() -> new SimpleDateFormat(\"yyyy-MM-dd\"));"),
        body("Корисно: з'єднання з БД у пулі потоків, генератори випадкових чисел. Важливо: завжди викликати remove() після використання (особливо у пулах потоків) для уникнення витоку пам'яті."),
        empty(),
        heading2("UncaughtExceptionHandler"),
        body("Якщо run() кидає непоймане виключення — потік завершується. Для обробки:"),
        code("worker.setUncaughtExceptionHandler((t, e) ->"),
        code("    System.err.println(\"Thread \" + t.getName() + \" failed: \" + e));"),
      ]
    },
    {
      id: 11,
      title: "Питання 11. Стрічковий алгоритм паралельного множення матриць",
      content: [
        heading2("Загальний контекст"),
        body("Стрічковий (row-striped) алгоритм — найпростіший та інтуїтивно зрозумілий підхід до паралельного множення матриць. Він ілюструє базовий принцип data parallelism і безпосередньо пов'язаний з поняттями Thread, Runnable, ExecutorService, закону Амдала та показниками ефективності."),
        empty(),
        heading2("Принцип алгоритму"),
        body("При множенні C = A × B, де A, B, C — матриці розміром N×N, рядки матриці A ('стрічки') розподіляються між потоками. Кожен потік обчислює відповідні рядки матриці C. Матриця B при цьому є спільним ресурсом для читання — синхронізація не потрібна, оскільки операція читання безпечна для кількох потоків."),
        code("// Послідовний алгоритм: O(N^3)"),
        code("for (int i = 0; i < N; i++)"),
        code("    for (int j = 0; j < N; j++)"),
        code("        for (int k = 0; k < N; k++)"),
        code("            C[i][j] += A[i][k] * B[k][j];"),
        empty(),
        heading2("Розподіл роботи між потоками"),
        body("Для T потоків і N рядків: потік i отримує рядки від i*(N/T) до (i+1)*(N/T) - 1. При N = 1000 і T = 4: потік 0 → рядки 0-249, потік 1 → 250-499, тощо. Навантаження рівномірне — ідеальний статичний балансинг."),
        code("ExecutorService pool = Executors.newFixedThreadPool(numThreads);"),
        code("List<Future<?>> futures = new ArrayList<>();"),
        code("int block = N / numThreads;"),
        code("for (int t = 0; t < numThreads; t++) {"),
        code("    final int start = t * block;"),
        code("    final int end = (t == numThreads-1) ? N : start + block;"),
        code("    futures.add(pool.submit(() -> {"),
        code("        for (int i = start; i < end; i++)"),
        code("            for (int j = 0; j < N; j++)"),
        code("                for (int k = 0; k < N; k++)"),
        code("                    C[i][j] += A[i][k] * B[k][j];"),
        code("    }));"),
        code("}"),
        code("for (Future<?> f : futures) f.get(); // sync point"),
        code("pool.shutdown();"),
        empty(),
        heading2("Ефективність та закон Амдала"),
        body("Ефективна паралельна частина: 99%+ (обчислення рядків). Послідовна частина: ініціалізація, збір результатів (мізерна). За законом Амдала при f ≈ 0.01 і T=8: S ≈ 7.5x — близьке до лінійного прискорення. На практиці обмежуючий фактор — пропускна здатність пам'яті та cache-miss для матриці B."),
        empty(),
        heading2("Vs MPI (стрічковий розподілений)"),
        body("В розподіленій версії (MPI) кожен процес отримує свої рядки A через MPI_Scatter, повну матрицю B через MPI_Bcast, виконує локальне множення, повертає рядки C через MPI_Gather. Master-процес (rank 0) координує розподіл і збір. Принцип той самий, але дані передаються через мережу, а не через спільну пам'ять."),
        empty(),
        heading2("Cache-оптимізація"),
        body("Цикл k (по рядку A і стовпцю B) призводить до non-sequential доступу до B. Транспонування B^T перед обчисленням дозволяє читати рядки обох матриць послідовно — значне покращення cache-поведінки для великих матриць."),
      ]
    },
    {
      id: 13,
      title: "Питання 13. Алгоритм Кеннона паралельного множення матриць",
      content: [
        heading2("Загальний контекст"),
        body("Алгоритм Кеннона (Cannon's Algorithm) — спеціалізований алгоритм для паралельного множення матриць у розподілених системах з пам'яттю що не є спільною. Він вирішує ключову проблему наївного підходу: надмірне використання пам'яті та великий об'єм комунікацій між процесами MPI."),
        empty(),
        heading2("Проблема наївного підходу"),
        body("При наївному розподілі рядків: Master надсилає кожному процесу весь B (N×N елементів). При p процесах — p передач всього B. Пам'ять: кожен процес зберігає весь B. Алгоритм Кеннона вирішує це, даючи кожному процесу лише блок матриці."),
        empty(),
        heading2("Принцип алгоритму"),
        body("Матриці A і B діляться на p блоків розміром (N/√p) × (N/√p), де p — кількість процесів (повний квадрат). Процеси розміщуються у двовимірній решітці √p × √p. Алгоритм виконується у три фази:"),
        bullet("Фаза 1 (вирівнювання): рядки блоків A зсуваються ліворуч на i позицій (рядок i), стовпці блоків B — вгору на j позицій (стовпець j)", ""),
        bullet("Фаза 2 (√p кроків): кожен процес множить свої блоки A[i][j] × B[i][j] і накопичує у C. Після кожного кроку A зсувається на 1 ліворуч, B — на 1 вгору", ""),
        bullet("Фаза 3 (збір): Master збирає блоки C від усіх процесів (MPI_Gather)", ""),
        empty(),
        heading2("MPI реалізація"),
        code("// Створення 2D декартової топології"),
        code("int dims[] = {sqrtp, sqrtp};"),
        code("MPI_Cart_create(MPI_COMM_WORLD, 2, dims, periods, 1, &cart_comm);"),
        code("MPI_Cart_coords(cart_comm, rank, 2, coords); // (row, col)"),
        code(""),
        code("// Зсув блоку A: cyclic shift left"),
        code("MPI_Cart_shift(cart_comm, 1, -coords[0], &src, &dst);"),
        code("MPI_Sendrecv_replace(A_block, ..., dst, 0, src, 0, cart_comm, &status);"),
        code(""),
        code("// Основні кроки"),
        code("for (int step = 0; step < sqrtp; step++) {"),
        code("    multiply_blocks(A_block, B_block, C_block); // локальне множення"),
        code("    shift_A_left(cart_comm, A_block);"),
        code("    shift_B_up(cart_comm, B_block);"),
        code("}"),
        empty(),
        heading2("Vs Алгоритм Фокса"),
        body("Алгоритм Фокса (Fox's Algorithm): на кожному кроці виконується broadcast блоку A вздовж рядка процесорної решітки, потім множення, потім cyclic shift B вгору. Фокс простіший у реалізації (broadcast замість двох зсувів), але має більше широкомовних операцій. Кеннон ефективніший за комунікаціями для великих решіток."),
        empty(),
        heading2("Переваги Кеннона"),
        bullet("Пам'ять: кожен процес зберігає лише N²/p елементів (замість N²)", ""),
        bullet("Комунікації: O(N²/√p) за крок, лише між сусідами у решітці", ""),
        bullet("Рівномірне навантаження: кожен процес виконує однакову роботу", ""),
        bullet("Масштабованість: ефективно до тисяч процесів", ""),
      ]
    },
    {
      id: 15,
      title: "Питання 15. Управління потоками в Java",
      content: [
        heading2("Загальний контекст"),
        body("Управління потоками охоплює весь цикл існування потоку: від запуску до коректного завершення, включно з синхронізацією, перериванням та збором результатів. Ці механізми критичні для всіх задач курсу: матричне множення, СМО, пошук у файлах."),
        empty(),
        heading2("join() — очікування завершення"),
        code("Thread[] workers = new Thread[numThreads];"),
        code("for (int t = 0; t < numThreads; t++) {"),
        code("    workers[t] = new Thread(new MatrixTask(t));"),
        code("    workers[t].start();"),
        code("}"),
        code("// Синхронізуємо: чекаємо всіх"),
        code("for (Thread w : workers) w.join();"),
        code("// Тут всі рядки C обчислені"),
        body("join(timeout) дозволяє задати максимальний час очікування. Якщо потік не завершився — продовжуємо без нього. Аналог у java.util.concurrent: Future.get(), CountDownLatch.await(), ForkJoinTask.join()."),
        empty(),
        heading2("interrupt() — кооперативне переривання"),
        body("Java використовує кооперативну модель переривання: interrupt() встановлює прапорець, але потік сам вирішує, коли зупинитись. Це дає можливість коректно завершити роботу (звільнити ресурси, зберегти стан)."),
        code("volatile boolean running = true;"),
        code(""),
        code("// У потоці: перевірка прапорця"),
        code("while (running && !Thread.currentThread().isInterrupted()) {"),
        code("    processNextTask();"),
        code("}"),
        code(""),
        code("// Переривання: sleep/wait кидають InterruptedException"),
        code("try { Thread.sleep(100); }"),
        code("catch (InterruptedException e) {"),
        code("    Thread.currentThread().interrupt(); // відновлюємо прапорець"),
        code("    return; // коректне завершення"),
        code("}"),
        empty(),
        heading2("yield() — поступка процесором"),
        body("Thread.yield() підказує планувальнику надати час іншим потокам. Не гарантія. Корисно у tight loop для CPU-bound задач. Рідко використовується у production. Планувальник може ігнорувати."),
        empty(),
        heading2("Пріоритети та планування"),
        body("setPriority(1-10): планувальник ОС враховує пріоритети при виборі наступного потоку. NORM_PRIORITY (5) — за замовчуванням. Підвищений пріоритет для критичних потоків (обробник запитів у Spring Boot). Понижений — для фонових задач."),
        empty(),
        heading2("Управління через ExecutorService"),
        body("У сучасному Java пряме управління Thread рідкісне. ExecutorService надає вищий рівень: submit() для завдань, Future для результатів, shutdown() для завершення, awaitTermination() для очікування. FixedThreadPool для СМО, ForkJoinPool для пошуку у файлах — це приклади управління пулами потоків."),
      ]
    },
    {
      id: 17,
      title: "Питання 17. Блокування потоку",
      content: [
        heading2("Загальний контекст"),
        body("Блокування (locking) — механізм захисту спільних ресурсів від одночасного доступу кількох потоків. Без блокувань race condition призводить до некоректних результатів: наприклад, два потоки одночасно читають і змінюють лічильник, втрачаючи оновлення."),
        empty(),
        heading2("synchronized — базовий механізм"),
        body("Кожен Java-об'єкт має вбудований монітор (intrinsic lock). synchronized блок/метод захоплює монітор та звільняє при виході (навіть при виключенні)."),
        code("// Синхронізований метод: монітор = this"),
        code("public synchronized void addResult(long count) {"),
        code("    totalFound += count; // захищена операція"),
        code("}"),
        code(""),
        code("// Синхронізований блок: явний об'єкт-монітор"),
        code("private final Object lock = new Object();"),
        code("synchronized (lock) { counter++; }"),
        body("Обмеження: не можна перервати очікування, немає try-lock, не підтримує кілька умов очікування."),
        empty(),
        heading2("ReentrantLock — явний лок"),
        code("private final ReentrantLock lock = new ReentrantLock();"),
        code(""),
        code("public void criticalSection() {"),
        code("    lock.lock();"),
        code("    try {"),
        code("        // захищений код"),
        code("    } finally {"),
        code("        lock.unlock(); // ОБОВ'ЯЗКОВО у finally"),
        code("    }"),
        code("}"),
        code(""),
        code("// tryLock: не чекає, якщо зайнятий"),
        code("if (lock.tryLock(100, TimeUnit.MILLISECONDS)) {"),
        code("    try { /* ... */ } finally { lock.unlock(); }"),
        code("}"),
        body("ReentrantLock реентерантний: один потік може захопити лок двічі. Підтримує fair ordering (FIFO) для уникнення starvation."),
        empty(),
        heading2("ReadWriteLock — для read-heavy навантаження"),
        body("Кілька потоків можуть одночасно читати, але лише один — писати. Ідеально для матриці B у стрічковому алгоритмі (якщо вона модифікується): всі потоки читають одночасно, запис — ексклюзивний."),
        code("ReadWriteLock rwLock = new ReentrantReadWriteLock();"),
        code("rwLock.readLock().lock();  // кілька одночасно"),
        code("rwLock.writeLock().lock(); // ексклюзивний"),
        empty(),
        heading2("StampedLock — оптимістичне читання"),
        body("Оптимістичне читання без блокування: спочатку читаємо, потім перевіряємо, чи не змінились дані. Якщо змінились — повторюємо з блокуванням. Максимальна продуктивність для read-heavy сценаріїв."),
        empty(),
        heading2("Deadlock та його запобігання"),
        body("Deadlock виникає при циклічному очікуванні локів. Запобігання: завжди захоплювати кілька локів в одному порядку; використовувати tryLock з таймаутом; уникати вкладених synchronized блоків. Виявлення: thread dump (jstack), VisualVM."),
      ]
    },
    {
      id: 19,
      title: "Питання 19. Синхронізовані методи",
      content: [
        heading2("Загальний контекст"),
        body("Синхронізовані методи та пов'язані механізми (wait/notify, volatile, AtomicXxx) є основою безпечної комунікації між потоками. Вони використовувались у паттерні Producer-Consumer, при зборі результатів паралельних обчислень, у СМО."),
        empty(),
        heading2("synchronized метод"),
        code("class ResultCollector {"),
        code("    private long total = 0;"),
        code(""),
        code("    // монітор = this"),
        code("    public synchronized void add(long value) {"),
        code("        total += value;"),
        code("    }"),
        code(""),
        code("    // static: монітор = ResultCollector.class"),
        code("    public static synchronized void staticOp() { ... }"),
        code("}"),
        empty(),
        heading2("wait() / notify() / notifyAll() — паттерн Producer-Consumer"),
        body("Основний механізм координації між потоками. Виклик лише всередині synchronized блоку."),
        code("class BoundedBuffer<T> {"),
        code("    private final Queue<T> queue = new LinkedList<>();"),
        code("    private final int capacity;"),
        code(""),
        code("    public synchronized void put(T item) throws InterruptedException {"),
        code("        while (queue.size() == capacity) wait(); // while, не if!"),
        code("        queue.add(item);"),
        code("        notifyAll(); // будимо всіх споживачів"),
        code("    }"),
        code(""),
        code("    public synchronized T take() throws InterruptedException {"),
        code("        while (queue.isEmpty()) wait();"),
        code("        T item = queue.poll();"),
        code("        notifyAll(); // будимо всіх виробників"),
        code("        return item;"),
        code("    }"),
        code("}"),
        body("Чому while, а не if? Spurious wakeups: потік може прокинутись без notify(). Перевірка умови у циклі захищає від помилок."),
        empty(),
        heading2("volatile — видимість між потоками"),
        body("volatile гарантує, що запис значення одним потоком буде видимий іншим (з main memory, не з кешу). Не гарантує атомарність складених операцій."),
        code("volatile boolean stopRequested = false; // видимий всім потокам"),
        code("// i++ НЕ атомарний навіть з volatile: read → increment → write"),
        empty(),
        heading2("Atomic класи — lock-free операції"),
        body("Базуються на CAS (Compare-And-Swap) — апаратна атомарна операція. Вища продуктивність ніж synchronized для простих операцій."),
        code("AtomicLong totalFound = new AtomicLong(0);"),
        code("// У кожному потоці:"),
        code("totalFound.addAndGet(localCount); // атомарно, без лока"),
        code("// Кращий варіант (Java 8+):"),
        code("LongAdder adder = new LongAdder(); // менше конкуренції"),
        empty(),
        heading2("Java Memory Model (JMM)"),
        body("Happens-Before: якщо A happens-before B, то всі зміни A видимі B. Правила: unlock HB lock того ж монітора; запис volatile HB читання того ж volatile; Thread.start() HB всім діям потоку; Thread.join() HB усьому коду після join(). Порушення HB → data race → undefined behavior."),
      ]
    },
    {
      id: 21,
      title: "Питання 21. Високорівневі способи управління потоками: java.util.concurrent",
      content: [
        heading2("Загальний контекст"),
        body("java.util.concurrent — бібліотека, що надає готові, правильно синхронізовані абстракції для паралельного програмування. Вона значно спрощує розробку порівняно з прямим використанням Thread і synchronized, і використовувалась у всіх практичних роботах курсу."),
        empty(),
        heading2("ExecutorService — керування задачами"),
        code("ExecutorService pool = Executors.newFixedThreadPool(4);"),
        code(""),
        code("// submit Runnable -> Future<?>"),
        code("Future<?> f1 = pool.submit(() -> computeRow(0));"),
        code(""),
        code("// submit Callable -> Future<T>"),
        code("Future<Long> f2 = pool.submit(() -> searchFiles(group));"),
        code("Long count = f2.get(); // блокуючий виклик"),
        code(""),
        code("// invokeAll: запускає всі, чекає всіх"),
        code("List<Future<Long>> results = pool.invokeAll(callableList);"),
        code(""),
        code("pool.shutdown();"),
        code("pool.awaitTermination(60, TimeUnit.SECONDS);"),
        empty(),
        heading2("BlockingQueue — паттерн Producer-Consumer"),
        code("BlockingQueue<Request> queue = new ArrayBlockingQueue<>(100);"),
        code("// Producer:"),
        code("queue.put(request);  // блокує при заповненні"),
        code("// Consumer:"),
        code("Request r = queue.take(); // блокує при порожній черзі"),
        body("Використовувалась в імітації СМО: клієнти (Producer) надходять з певною інтенсивністю λ, сервери (Consumer через FixedThreadPool) обслуговують з інтенсивністю μ. BlockingQueue — черга клієнтів."),
        empty(),
        heading2("CountDownLatch і CyclicBarrier"),
        code("// CountDownLatch: N потоків сигналізують, 1 чекає"),
        code("CountDownLatch latch = new CountDownLatch(numThreads);"),
        code("// У кожному потоці після завершення:"),
        code("latch.countDown();"),
        code("// Головний потік:"),
        code("latch.await(); // чекає countDown() від усіх"),
        code(""),
        code("// CyclicBarrier: всі потоки чекають один одного"),
        code("CyclicBarrier barrier = new CyclicBarrier(numThreads, () -> {"),
        code("    System.out.println(\"Всі завершили фазу!\");"),
        code("});"),
        code("// У кожному потоці:"),
        code("barrier.await(); // фаза-синхронізація"),
        body("CyclicBarrier повторно використовуваний (як MPI_Barrier). Корисний у ітераційних алгоритмах де потоки мають синхронізуватись між ітераціями."),
        empty(),
        heading2("Semaphore і CompletableFuture"),
        body("Semaphore обмежує кількість одночасних потоків у секції. CompletableFuture (Java 8+) — компонований асинхронний pipeline: supplyAsync().thenApply().thenCombine(). У Spring Boot застосунку: async обробка запитів на множення матриць через CompletableFuture."),
      ]
    },
    {
      id: 23,
      title: "Питання 23. Пули потоків",
      content: [
        heading2("Загальний контекст"),
        body("Пули потоків вирішують фундаментальну проблему: створення нового Thread — дорога операція (виділення пам'яті для стеку, реєстрація в ОС). При сотнях задач на секунду (наприклад, у СМО або Spring Boot) накладні витрати неприйнятні. Пул підтримує набір готових потоків і направляє задачі до них."),
        empty(),
        heading2("Типи пулів (Executors factory)"),
        bullet("newFixedThreadPool(n) — рівно n потоків завжди. Черга — LinkedBlockingQueue (необмежена). Для задач з передбачуваним навантаженням (імітація СМО: n потоків = n серверів)", ""),
        bullet("newCachedThreadPool() — потоки створюються по потребі, кешуються 60 сек. Для burst навантажень з короткими задачами", ""),
        bullet("newSingleThreadExecutor() — 1 потік, задачі виконуються послідовно. Для серіалізації доступу до ресурсу", ""),
        bullet("newScheduledThreadPool(n) — планувальник: з затримкою або повторенням. Для моніторингу, таймерів", ""),
        bullet("ForkJoinPool.commonPool() — спільний пул для паралельних стрімів і ForkJoinTask", ""),
        empty(),
        heading2("ThreadPoolExecutor: повний контроль"),
        code("ThreadPoolExecutor executor = new ThreadPoolExecutor("),
        code("    4,    // corePoolSize: завжди живих потоків"),
        code("    8,    // maximumPoolSize: максимум при черзі"),
        code("    30, TimeUnit.SECONDS, // keepAlive для extra потоків"),
        code("    new ArrayBlockingQueue<>(50), // обмежена черга"),
        code("    new ThreadFactory() { ... }, // власна фабрика потоків"),
        code("    new CallerRunsPolicy() // при переповненні: caller виконує сам"),
        code(");"),
        body("RejectedExecutionHandler стратегії при переповненні черги: AbortPolicy (кидає RejectedExecutionException), CallerRunsPolicy (виконує у потоці caller — природний backpressure), DiscardPolicy (мовчки відкидає), DiscardOldestPolicy (відкидає найстарішу)."),
        empty(),
        heading2("СМО на FixedThreadPool"),
        body("Система масового обслуговування (СМО) — класична модель для аналізу черг обслуговування. Параметри: λ (інтенсивність надходження клієнтів), μ (інтенсивність обслуговування одним сервером), n (кількість серверів)."),
        code("ExecutorService servers = Executors.newFixedThreadPool(numServers);"),
        code("ScheduledExecutorService generator = Executors.newScheduledThreadPool(1);"),
        code(""),
        code("// Генератор клієнтів з інтенсивністю lambda"),
        code("generator.scheduleAtFixedRate(() -> {"),
        code("    servers.submit(() -> { // клієнт"),
        code("        Thread.sleep((long)(1000 / mu)); // час обслуговування"),
        code("    });"),
        code("}, 0, (long)(1000/lambda), TimeUnit.MILLISECONDS);"),
        body("Метрики: avg waiting time, queue length, server utilization. Теоретично перевіряється формулами Ерланга (M/M/n черга)."),
        empty(),
        heading2("ForkJoinPool і work-stealing"),
        body("Кожен потік має двосторонню deque. Задачі додаються на початок власної черги. Вільний потік 'краде' задачі з кінця чужої черги — мінімальна конкуренція. Оптимальний для нерівномірного навантаження (різний розмір підзадач). Використовувався для пошуку слів у файлах."),
      ]
    },
    {
      id: 25,
      title: "Питання 25. ForkJoinFramework",
      content: [
        heading2("Загальний контекст"),
        body("ForkJoinFramework — Java-реалізація парадигми divide-and-conquer для паралельних обчислень. Ключові переваги: автоматичне балансування навантаження через work-stealing, ефективна рекурсивна декомпозиція, мінімальний overhead синхронізації."),
        empty(),
        heading2("Ключові класи"),
        bullet("ForkJoinPool — спеціалізований пул потоків з підтримкою work-stealing", ""),
        bullet("RecursiveTask<V> — задача що повертає результат (compute() → V)", ""),
        bullet("RecursiveAction — задача без результату (compute() → void)", ""),
        bullet("ForkJoinTask — базовий абстрактний клас", ""),
        empty(),
        heading2("Пошук слів у файлах"),
        body("Практична задача курсу: знайти всі входження слова у великому наборі файлів. Список файлів рекурсивно ділиться на дві групи до досягнення порогового розміру (threshold)."),
        code("class SearchTask extends RecursiveTask<Long> {"),
        code("    private static final int THRESHOLD = 5; // файлів на задачу"),
        code("    private final List<Path> files;"),
        code("    private final String word;"),
        code(""),
        code("    @Override"),
        code("    protected Long compute() {"),
        code("        if (files.size() <= THRESHOLD) {"),
        code("            return searchSequential(files, word); // базовий випадок"),
        code("        }"),
        code("        int mid = files.size() / 2;"),
        code("        SearchTask left = new SearchTask(files.subList(0, mid), word);"),
        code("        SearchTask right = new SearchTask(files.subList(mid, files.size()), word);"),
        code("        left.fork(); // відправити у пул"),
        code("        long rightResult = right.compute(); // виконати локально"),
        code("        long leftResult = left.join(); // чекати результату"),
        code("        return leftResult + rightResult;"),
        code("    }"),
        code("}"),
        code(""),
        code("ForkJoinPool pool = new ForkJoinPool(); // або commonPool()"),
        code("long total = pool.invoke(new SearchTask(allFiles, \"target\"));"),
        empty(),
        heading2("Work-Stealing у деталях"),
        body("Кожен потік ForkJoinPool має двосторонню deque (ArrayDeque). Нові підзадачі додаються на початок власної deque (LIFO — cache-friendly). Вільний потік бере задачі з кінця чужої deque (FIFO — менша конкуренція за блокування). Це дозволяє ефективно розподіляти нерівномірне навантаження без централізованого планувальника."),
        empty(),
        heading2("Вибір threshold"),
        body("Замалий threshold → забагато task objects, overhead від fork/join > корисної роботи. Завеликий threshold → нерівномірне навантаження, деякі потоки простоюють. Оптимально: емпірично підбирається або залежить від розміру даних. Для файлів: 1-10 файлів на задачу."),
        empty(),
        heading2("invokeAll оптимізація"),
        code("// Замість left.fork() + right.compute() + left.join():"),
        code("invokeAll(left, right); // симетрично ділить роботу"),
        code("return left.join() + right.join();"),
        body("invokeAll виконує одну задачу локально, іншу форкає — автоматично оптимально."),
      ]
    },
    {
      id: 27,
      title: "Питання 27. Модель обчислень у вигляді графа «операції—операнди»",
      content: [
        heading2("Загальний контекст"),
        body("Граф операцій і операндів — математична модель для аналізу паралельного потенціалу програми. Вона дозволяє визначити, які операції можна виконати паралельно, а які мають суворо послідовний порядок."),
        empty(),
        heading2("Структура графа"),
        body("Граф залежностей даних (Data Dependence Graph, DDG) — це DAG (Directed Acyclic Graph, орієнтований граф без циклів). Вузли — операції (обчислення, присвоєння). Ребра — потоки даних: ребро від A до B означає, що B використовує результат A."),
        bullet("Справжня залежність (RAW — Read After Write): B читає те, що A записала", ""),
        bullet("Антизалежність (WAR — Write After Read): B записує те, що A читала", ""),
        bullet("Вихідна залежність (WAW — Write After Write): A і B записують в одне місце", ""),
        empty(),
        heading2("Критичний шлях"),
        body("Критичний шлях — найдовший шлях у графі від початкового вузла до кінцевого (з урахуванням вагів вузлів — тривалості операцій). Час паралельного виконання з нескінченною кількістю процесорів дорівнює довжині критичного шляху — це нижня межа часу виконання."),
        body("Зв'язок з законом Амдала: послідовна частина (f) відповідає критичному шляху — ланцюжку залежних операцій, що не можна розпаралелити."),
        empty(),
        heading2("Застосування у матричному множенні"),
        body("У послідовному алгоритмі C[i][j] = Σ A[i][k]*B[k][j] для різних (i,j) операції незалежні — жодних залежностей даних між ними. Це означає максимальний паралелізм: всі рядки можна обчислювати одночасно. Граф має ширину N (кількість рядків) і глибину N (операції всередині рядка)."),
        empty(),
        heading2("Зв'язок з ForkJoinPool"),
        body("RecursiveTask утворює явне дерево залежностей: батьківська задача залежить від дочірніх. fork() — виконати незалежну гілку, join() — точка залежності. CompletableFuture утворює DAG неявно через thenApply(), thenCombine(), allOf()."),
        code("CompletableFuture<Long> left = CompletableFuture.supplyAsync(leftTask);"),
        code("CompletableFuture<Long> right = CompletableFuture.supplyAsync(rightTask);"),
        code("CompletableFuture<Long> result = left.thenCombine(right, Long::sum);"),
        body("Тут left і right — паралельні вузли графу; thenCombine — вузол з двома вхідними ребрами залежності."),
        empty(),
        heading2("Scheduling problem"),
        body("Маючи граф залежностей і p процесорів, задача планувальника — призначити вузли на процесори мінімізуючи час. NP-hard у загальному випадку. Евристики: List Scheduling (критичний шлях перший), Level Scheduling (вузли одного рівня на один слот). ForkJoinPool вирішує це динамічно через work-stealing."),
      ]
    },
    {
      id: 29,
      title: "Питання 29. Показники ефективності паралельного алгоритму",
      content: [
        heading2("Загальний контекст"),
        body("Показники ефективності дозволяють кількісно оцінити, наскільки добре паралельний алгоритм використовує наявні ресурси. Вони пов'язані з законом Амдала і є інструментом аналізу всіх практичних задач курсу."),
        empty(),
        heading2("Прискорення (Speedup)"),
        body("S(p) = T(1) / T(p), де T(1) — час послідовного алгоритму, T(p) — час паралельного з p процесорами/потоками."),
        bullet("Лінійне (ідеальне): S(p) = p — кожне ядро дає рівно 1x приріст", ""),
        bullet("Суперлінійне: S(p) > p — рідкісно, можливо через cache effects (задача вміщується в кеш кожного ядра)", ""),
        bullet("Субоптимальне: S(p) < p — завжди на практиці через overhead", ""),
        body("Вимірювання у Java: System.nanoTime() до і після паралельного блоку. Порівнювати з чистим послідовним кодом (не з 1 потоком у пулі — є overhead ExecutorService)."),
        empty(),
        heading2("Ефективність (Efficiency)"),
        body("E(p) = S(p) / p = T(1) / (p × T(p)). Показує середнє завантаження кожного процесора. E=1 (100%) — ідеально. E=0.5 (50%) — половина часу простоюють. При зростанні p і фіксованій задачі E зменшується (більше комунікацій, синхронізацій)."),
        empty(),
        heading2("Накладні витрати (Overhead)"),
        body("T_overhead = p × T(p) - T(1) — різниця між фактичними витраченими ресурсами і мінімально необхідними. Складові: T_comm (передача даних, в MPI — через мережу), T_sync (синхронізація: join(), barrier, lock), T_idle (простій через незбалансованість), T_extra (дублікат обчислень у паралельній версії)."),
        empty(),
        heading2("Масштабованість (Scalability)"),
        bullet("Сильна (strong scaling): збільшуємо p при фіксованій задачі. За законом Амдала обмежена послідовною частиною.", ""),
        bullet("Слабка (weak scaling): збільшуємо і p, і розмір задачі пропорційно. Закон Густавсона. E ≈ const — ознака доброго масштабування.", ""),
        bullet("Isoefficiency function W=f(p): визначає як треба збільшувати задачу при зростанні p для збереження E. Лінійна f(p) — добре масштабування.", ""),
        empty(),
        heading2("Вартість (Cost)"),
        body("C(p) = p × T(p) — загальна витрачена процесорна робота. Оптимальний алгоритм: C(p) = O(T(1)) — паралельна версія не виконує значно більше роботи. Якщо C(p) >> T(1) — алгоритм неефективний попри прискорення."),
        empty(),
        heading2("Практичний аналіз задач курсу"),
        bullet("Стрічковий алгоритм: висока ефективність (E ≈ 0.9+) через мінімальну синхронізацію", ""),
        bullet("ForkJoin пошук файлів: E залежить від threshold та розподілу розміру файлів", ""),
        bullet("MPI Кеннон: E знижується з ростом p через комунікаційний overhead", ""),
      ]
    },
    {
      id: 31,
      title: "Питання 31. Закон Амдала. Ефект Амдала",
      content: [
        heading2("Загальний контекст"),
        body("Закон Амдала — фундаментальне обмеження паралельних обчислень. Він пояснює, чому нескінченна кількість процесорів не дає нескінченного прискорення і є теоретичним підґрунтям для всіх практичних задач курсу."),
        empty(),
        heading2("Формулювання"),
        body("Нехай f — частка часу, яку займає послідовна частина програми (0 < f < 1). Тоді максимальне прискорення з p процесорами:"),
        body("S(p) ≤ 1 / (f + (1-f)/p)"),
        body("При p → ∞:  S_max = 1/f"),
        empty(),
        heading2("Ефект Амдала (числові приклади)"),
        bullet("f = 50%: S_max = 2x (ніяка кількість ядер не дасть більше)", ""),
        bullet("f = 10%: S_max = 10x", ""),
        bullet("f = 5%:  S_max = 20x", ""),
        bullet("f = 1%:  S_max = 100x", ""),
        bullet("f = 0.1%: S_max = 1000x — потрібно < 0.1% послідовного для кластеру 1000 вузлів!", ""),
        empty(),
        heading2("Джерела послідовних секцій у Java"),
        body("Аналіз практичних задач:"),
        bullet("join() / Future.get() — синхронізаційна точка: всі потоки чекають найповільнішого", ""),
        bullet("synchronized блоки — лише один потік у критичній секції", ""),
        bullet("Ініціалізація даних — розподіл матриці між потоками до start()", ""),
        bullet("I/O операції — читання файлів (якщо не паралельне)", ""),
        bullet("MPI_Barrier — всі процеси чекають найповільнішого", ""),
        bullet("Master-процес у MPI — scatter/gather є практично послідовними операціями", ""),
        empty(),
        heading2("Закон Густавсона (scaled speedup)"),
        body("Амдал вважає задачу фіксованого розміру. Але на практиці при більших ресурсах вирішуються більші задачі. Закон Густавсона: S = p - f_s × (p-1), де f_s — частка послідовного при p процесорах. При зростанні p і W: послідовна частина залишається константою, а паралельна зростає → ефективне масштабування."),
        empty(),
        heading2("Практичні висновки для Java"),
        body("При реалізації паралельних алгоритмів: мінімізувати synchronized блоки (lock-free через AtomicXxx або LongAdder), розпаралелювати ініціалізацію та I/O (паралельне читання файлів у ForkJoin), використовувати неблокуючі операції MPI де можливо, профілювати для виявлення послідовних bottleneck (VisualVM, YourKit)."),
      ]
    },
    {
      id: 33,
      title: "Питання 33. Оцінка ефективності паралельних обчислень",
      content: [
        heading2("Загальний контекст"),
        body("Оцінка ефективності — методологія вимірювання та аналізу продуктивності паралельних програм. Без належної оцінки неможливо визначити, чи дає паралелізм очікуваний результат та де вузькі місця."),
        empty(),
        heading2("Вимірювання у Java"),
        code("// Правильна методологія:"),
        code("// 1. Прогрів JVM (JIT компіляція)"),
        code("for (int i = 0; i < 3; i++) runAlgorithm(); // warmup"),
        code(""),
        code("// 2. Вимірювання з нано-точністю"),
        code("long start = System.nanoTime();"),
        code("long result = pool.invoke(new SearchTask(files, word));"),
        code("long elapsed = System.nanoTime() - start;"),
        code("System.out.printf(\"Time: %.3f ms%n\", elapsed / 1e6);"),
        code(""),
        code("// 3. Статистика по кількох запусках"),
        code("// Відкидати min і max, усереднювати решту"),
        body("Джерела похибок: JIT-компіляція (перші запуски повільніші), GC-паузи, OS scheduling, thermal throttling, гіпертредінг. JMH (Java Microbenchmark Harness) — стандарт для точного бенчмаркінгу."),
        empty(),
        heading2("Балансування навантаження"),
        body("Час паралельного виконання визначається найповільнішим потоком (weakest link). При нерівному розподілі: T(p) ≈ T_max_thread >> T_avg_thread. Метрики дисбалансу: відхилення часів потоків від середнього. Рішення: ForkJoinPool work-stealing (динамічне), дрібніший розмір задач (більше можливостей для балансування)."),
        empty(),
        heading2("Аналіз масштабування"),
        body("Правильний сильний scaling тест: фіксуємо матрицю 2000×2000. Вимірюємо T(1), T(2), T(4), T(8). Обчислюємо S(p), E(p). Якщо E падає різко — є значний overhead або незбалансованість. Grafік S(p) vs ідеальне S=p показує розрив — аналіз де він з'являється."),
        empty(),
        heading2("Профілювання Java"),
        bullet("VisualVM — вбудований, thread dump, CPU/memory profiling", ""),
        bullet("async-profiler — flame graphs, низький overhead, підходить для production", ""),
        bullet("JFR (Java Flight Recorder) — детальний event recording", ""),
        bullet("jstack — швидкий thread dump для аналізу deadlock, blocking", ""),
        empty(),
        heading2("Bottleneck аналіз"),
        body("Типові вузькі місця: shared lock (synchronized) — всі потоки чекають → AtomicXxx або ConcurrentHashMap. Memory bandwidth — усі потоки одночасно читають велику матрицю → cache-friendly layout. I/O bound — читання файлів для пошуку → async NIO, паралельне читання. Network (MPI) — багато дрібних повідомлень → агрегація, batch."),
      ]
    },
    {
      id: 35,
      title: "Питання 35. Архітектура розподілених систем. Таксономія Фліна",
      content: [
        heading2("Загальний контекст"),
        body("Архітектура розподілених систем — основа для розуміння MPI, Grid та розподіленого матричного множення. Таксономія Фліна дає систематичну класифікацію обчислювальних систем."),
        empty(),
        heading2("Таксономія Фліна"),
        body("Класифікація за двома потоками: Instructions (I) і Data (D). Кожен може бути Single або Multiple:"),
        bullet("SISD (Single Instruction, Single Data) — класичний послідовний комп'ютер. Фон Нейманівська архітектура. Один потік виконання, одне значення за раз.", ""),
        bullet("SIMD (Single Instruction, Multiple Data) — одна інструкція над вектором даних. GPU (тисячі ядер), AVX інструкції процесора. Ефективно для однорідних обчислень (матриці, сигнали).", ""),
        bullet("MISD (Multiple Instruction, Single Data) — рідкісна. Конвеєрні процесори, fault-tolerant системи (кілька процесорів обробляють ті ж дані, голосування за результатом).", ""),
        bullet("MIMD (Multiple Instruction, Multiple Data) — найпоширеніша для паралельних обчислень. Кожен процесор виконує свою послідовність інструкцій над своїми даними. Багатоядерні CPU, кластери MPI.", ""),
        empty(),
        heading2("MIMD: підкатегорії"),
        bullet("Shared Memory SMP — всі процесори мають спільну пам'ять. Java threads. Обмежена масштабованість (~100+ ядер).", ""),
        bullet("Distributed Memory — кожен вузол окремий комп'ютер, зв'язані мережею. MPI. Необмежена теоретично масштабованість.", ""),
        bullet("NUMA (Non-Uniform Memory Access) — гібрид: кілька вузлів зі спільною пам'яттю, але різна латентність для локальної/чужої пам'яті.", ""),
        empty(),
        heading2("Архітектура розподілених систем"),
        body("Ключові характеристики: відсутність спільного годинника (проблема синхронізації часу), відсутність спільної пам'яті (обмін через повідомлення), часткові відмови вузлів (fault tolerance), мережевий зв'язок з латентністю (на відміну від RAM)."),
        body("Моделі: Master-Worker (наш стрічковий алгоритм MPI: master розподіляє рядки), Peer-to-Peer (алгоритм Кеннона: рівноправні процеси обмінюються блоками), Pipeline, MapReduce."),
        empty(),
        heading2("Зв'язок з Spring Boot"),
        body("Spring Boot застосунок для матричного множення — мікросервісна архітектура (MIMD на рівні сервісів): клієнт надсилає REST запит, сервер обробляє (може розподіляти роботу між потоками пулу або вузлами кластеру), повертає результат. Це розподілена система де клієнт і сервер — різні процеси."),
      ]
    },
    {
      id: 37,
      title: "Питання 37. Стандарти та технології обміну повідомленнями в розподілених системах",
      content: [
        heading2("Загальний контекст"),
        body("Технології обміну повідомленнями — основа розподілених обчислень. Вибір технології визначає продуктивність, масштабованість і складність розробки системи. У курсі ми використовували MPI та REST (Spring Boot)."),
        empty(),
        heading2("MPI (Message Passing Interface)"),
        body("Стандарт де-факто для HPC. Специфікація інтерфейсу (не реалізація): OpenMPI, MPICH, MVAPICH, MS-MPI — різні реалізації. Нативно: C/C++/Fortran. Для Java: MPJ Express, mpiJava. Ключові переваги: найвища продуктивність, мінімальна латентність (спеціалізоване апаратне забезпечення InfiniBand), стандартизація."),
        empty(),
        heading2("Сокети TCP/UDP"),
        body("Низькорівневий API: java.net.Socket (TCP) та DatagramSocket (UDP). TCP — надійна доставка, порядок збережено, але overhead. UDP — максимальна швидкість, без гарантій. Java NIO (java.nio) — асинхронні сокети для масштабованих серверів. Основа для більшості протоколів вищого рівня."),
        empty(),
        heading2("REST / HTTP"),
        code("// Spring Boot: REST endpoint для матричного множення"),
        code("@RestController"),
        code("public class MatrixController {"),
        code("    @PostMapping(\"/multiply\")"),
        code("    public MatrixResult multiply(@RequestBody MatrixRequest req) {"),
        code("        // запуск паралельного множення"),
        code("        return matrixService.multiplyAsync(req).join();"),
        code("    }"),
        code("}"),
        body("REST — основа мікросервісів. JSON/XML серіалізація — overhead для чисельних даних. Spring Boot автоматично обробляє серіалізацію/десеріалізацію. Підходить для occasional computations, не для tight loop HPC."),
        empty(),
        heading2("Message Brokers"),
        body("RabbitMQ, Apache Kafka, ActiveMQ — асинхронна комунікація через брокер. Decoupling: Producer і Consumer незалежні, брокер буферизує. Персистентність: повідомлення зберігаються до доставки. Паттерн Producer-Consumer з BlockingQueue у Java — аналог message broker у рамках JVM."),
        empty(),
        heading2("gRPC"),
        body("Google Remote Procedure Call: HTTP/2 + Protocol Buffers (бінарна серіалізація). 5-10x ефективніше JSON/REST для чисельних даних. Стрімінг (сервер, клієнт, двосторонній). Генерація Java-коду з .proto файлів. Підходить для міжсервісних викликів з числовими обчисленнями."),
      ]
    },
    {
      id: 39,
      title: "Питання 39. Методи обміну повідомленнями MPI один до одного та їх застосування",
      content: [
        heading2("Загальний контекст"),
        body("P2P (Point-to-Point) комунікації MPI — основа для побудови будь-яких паралельних алгоритмів у розподілених системах. Блокуючі та неблокуючі операції мають різні характеристики продуктивності та різні ризики."),
        empty(),
        heading2("Блокуючі операції: MPI_Send / MPI_Recv"),
        code("// Процес 0: надсилаємо рядки матриці процесу 1"),
        code("MPI_Send(A_rows, count, MPI_DOUBLE, 1, tag, MPI_COMM_WORLD);"),
        code("// Блокує до завершення передачі буфера"),
        code(""),
        code("// Процес 1: отримуємо"),
        code("MPI_Recv(buffer, count, MPI_DOUBLE, 0, tag, MPI_COMM_WORLD, &status);"),
        code("// Блокує до отримання повідомлення"),
        body("Параметри: буфер, кількість елементів, тип даних (MPI_INT, MPI_DOUBLE), ранг партнера, тег (розрізнення повідомлень), комунікатор, статус."),
        body("Небезпека deadlock: якщо обидва процеси одночасно роблять MPI_Send один одному — обидва блокуються. Рішення: MPI_Sendrecv або неблокуючі операції."),
        empty(),
        heading2("Неблокуючі операції: MPI_Isend / MPI_Irecv"),
        code("MPI_Request request;"),
        code("MPI_Isend(A_rows, count, MPI_DOUBLE, dest, tag,"),
        code("          MPI_COMM_WORLD, &request);"),
        code("// Повертає негайно! Обчислення перекривають комунікацію"),
        code("compute_local_part();"),
        code("// Чекаємо завершення передачі"),
        code("MPI_Wait(&request, &status);"),
        code(""),
        code("// Перевірка без блокування:"),
        code("int flag;"),
        code("MPI_Test(&request, &flag, &status);"),
        code("if (flag) { /* передача завершена */ }"),
        body("Головна перевага: overlap обчислень і комунікацій. Поки мережа передає дані — процесор обчислює. Це приховує latency мережі."),
        empty(),
        heading2("MPI_Sendrecv — безпечний обмін"),
        code("// Алгоритм Кеннона: циклічний зсув блоків"),
        code("MPI_Sendrecv(A_block, blockSize, MPI_DOUBLE, dest_rank, 0,"),
        code("             A_buffer, blockSize, MPI_DOUBLE, src_rank, 0,"),
        code("             cart_comm, &status);"),
        body("Одночасно відправляє і отримує — не виникає deadlock при кільцевій топології. Вбудований буфер для обміну."),
        empty(),
        heading2("Теги та комунікатори"),
        body("Tag — ціле число для розрізнення різних типів повідомлень від одного джерела (наприклад, рядки матриці vs метадані). MPI_ANY_TAG — прийняти будь-який тег. Комунікатор MPI_COMM_WORLD — всі процеси. Власний комунікатор (MPI_Comm_create) — підмножина процесів для ізоляції алгоритмів."),
      ]
    },
    {
      id: 41,
      title: "Питання 41. OpenMPI: особливості побудови програми та основні методи",
      content: [
        heading2("Загальний контекст"),
        body("OpenMPI — найпоширеніша open-source реалізація стандарту MPI. Саме на ній базувались наші практичні роботи з розподіленого матричного множення. Знання структури програми і основних методів — необхідна умова розробки ефективних розподілених алгоритмів."),
        empty(),
        heading2("Структура MPI програми"),
        code("int main(int argc, char* argv[]) {"),
        code("    // 1. Ініціалізація MPI середовища"),
        code("    MPI_Init(&argc, &argv);"),
        code(""),
        code("    int rank, size;"),
        code("    // 2. Отримати свій ранг (номер процесу)"),
        code("    MPI_Comm_rank(MPI_COMM_WORLD, &rank);"),
        code("    // 3. Отримати загальну кількість процесів"),
        code("    MPI_Comm_size(MPI_COMM_WORLD, &size);"),
        code(""),
        code("    // 4. Логіка: master або worker"),
        code("    if (rank == 0) { /* Master: розподіляти, збирати */ }"),
        code("    else           { /* Worker: обчислювати */ }"),
        code(""),
        code("    // 5. Завершення"),
        code("    MPI_Finalize();"),
        code("    return 0;"),
        code("}"),
        code("// Компіляція: mpicc program.c -o program"),
        code("// Запуск:     mpirun -np 4 ./program"),
        empty(),
        heading2("Колективні операції"),
        code("// Розподіл даних від Master до всіх:"),
        code("MPI_Scatter(A, N/size, MPI_DOUBLE, A_local, N/size,"),
        code("            MPI_DOUBLE, 0, MPI_COMM_WORLD);"),
        code(""),
        code("// Широкомовлення: 0 надсилає B всім"),
        code("MPI_Bcast(B, N*N, MPI_DOUBLE, 0, MPI_COMM_WORLD);"),
        code(""),
        code("// Збирання результатів:"),
        code("MPI_Gather(C_local, N/size, MPI_DOUBLE, C, N/size,"),
        code("           MPI_DOUBLE, 0, MPI_COMM_WORLD);"),
        code(""),
        code("// Редукція: sum по всіх процесах"),
        code("MPI_Reduce(&local_sum, &global_sum, 1, MPI_DOUBLE,"),
        code("           MPI_SUM, 0, MPI_COMM_WORLD);"),
        code(""),
        code("// Бар'єр (як Java CyclicBarrier):"),
        code("MPI_Barrier(MPI_COMM_WORLD);"),
        empty(),
        heading2("2D топологія для алгоритму Кеннона"),
        code("int dims[2] = {sqrtp, sqrtp}, periods[2] = {1, 1};"),
        code("MPI_Comm cart_comm;"),
        code("MPI_Cart_create(MPI_COMM_WORLD, 2, dims, periods, 1, &cart_comm);"),
        code(""),
        code("int coords[2];"),
        code("MPI_Cart_coords(cart_comm, rank, 2, coords);"),
        code("// coords[0] = рядок решітки, coords[1] = стовпець"),
        code(""),
        code("int left, right, up, down;"),
        code("MPI_Cart_shift(cart_comm, 1, 1, &left, &right); // горизонт"),
        code("MPI_Cart_shift(cart_comm, 0, 1, &up, &down);   // вертикаль"),
        empty(),
        heading2("Вимірювання часу"),
        code("double t_start = MPI_Wtime(); // секунди від epoch"),
        code("// ... алгоритм ..."),
        code("double t_end = MPI_Wtime();"),
        code("double elapsed = t_end - t_start;"),
        body("MPI_Wtime() — точні double-precision секунди. Для коректного вимірювання: MPI_Barrier перед і після для синхронізації."),
      ]
    },
    {
      id: 43,
      title: "Питання 43. Алгоритми паралельного сортування",
      content: [
        heading2("Загальний контекст"),
        body("Паралельне сортування — класична задача, що демонструє різні підходи до розпаралелювання: divide-and-conquer (ForkJoin), data parallelism, pipeline. Java надає вбудований паралельний сорт, а MPI дозволяє сортувати розподілені масиви."),
        empty(),
        heading2("Arrays.parallelSort() — Java вбудований"),
        code("int[] arr = new int[10_000_000];"),
        code("// Ефективне паралельне сортування:"),
        code("Arrays.parallelSort(arr);"),
        code("// Або підмасив:"),
        code("Arrays.parallelSort(arr, fromIndex, toIndex);"),
        body("Використовує ForkJoin parallel merge sort. Автоматично вибирає threshold для переходу на послідовний InsertionSort. При arr.length < 8192 — завжди послідовний (overhead пулу невиправданий). Значно швидший за Arrays.sort() для великих масивів на багатоядерних CPU."),
        empty(),
        heading2("Паралельний MergeSort через ForkJoin"),
        code("class ParallelMergeSort extends RecursiveAction {"),
        code("    private final int[] arr;"),
        code("    private final int lo, hi;"),
        code("    private static final int THRESHOLD = 1000;"),
        code(""),
        code("    protected void compute() {"),
        code("        if (hi - lo <= THRESHOLD) {"),
        code("            Arrays.sort(arr, lo, hi); // послідовний"),
        code("            return;"),
        code("        }"),
        code("        int mid = (lo + hi) / 2;"),
        code("        invokeAll("),
        code("            new ParallelMergeSort(arr, lo, mid),"),
        code("            new ParallelMergeSort(arr, mid, hi)"),
        code("        );"),
        code("        merge(arr, lo, mid, hi); // послідовний merge"),
        code("    }"),
        code("}"),
        body("Обмеження: merge операція — потенційна послідовна секція (за законом Амдала). Паралельний merge складніший, але можливий."),
        empty(),
        heading2("Odd-Even Sort у MPI"),
        body("Простий алгоритм для розподіленого сортування. Кожен процес зберігає відсортований підмасив. Алгоритм: p/2 пар процесів обмінюються сусідніми підмасивами та зберігають мінімум/максимум (odd step), потім інші пари (even step). Через n ітерацій масив відсортований. Недоліки: O(n) ітерацій MPI_Sendrecv — не ефективний для великих p, але простий у реалізації."),
        empty(),
        heading2("Sample Sort (PSRS)"),
        body("Parallel Sort by Regular Sampling: ефективний розподілений алгоритм. Кожен процес сортує свій блок, вибирає 'зразки'. Master збирає зразки, сортує, вибирає splitters. Кожен процес перерозподіляє елементи по 'кошиках' (buckets) на основі splitters. Фінальне злиття. Дає рівномірне навантаження, хороший для кластерних систем."),
      ]
    },
    {
      id: 45,
      title: "Питання 45. Оцінювання продуктивності паралельних алгоритмів в розподілених системах",
      content: [
        heading2("Загальний контекст"),
        body("Оцінка продуктивності у розподілених системах суттєво складніша ніж для shared-memory: додаються мережеві затримки, нерівномірна завантаженість вузлів, різна швидкість мереж. MPI надає власні інструменти для вимірювань."),
        empty(),
        heading2("Модель вартості комунікацій (α-β модель)"),
        body("Час передачі m байт: T_comm = α + m/β"),
        bullet("α (latency) — час ініціалізації передачі, ~1-10 мкс (InfiniBand), ~100 мкс (Ethernet). Домінує для малих повідомлень.", ""),
        bullet("β (bandwidth) — пропускна здатність, ~10-200 GB/s (InfiniBand). Домінує для великих повідомлень.", ""),
        body("Висновок: мінімізуємо кількість дрібних повідомлень (aggregation). Колективні операції (MPI_Bcast, MPI_Reduce) оптимізовані під топологію мережі — ефективніші ніж p P2P операцій."),
        empty(),
        heading2("Вимірювання у MPI"),
        code("MPI_Barrier(MPI_COMM_WORLD); // синхронізація перед вимірюванням"),
        code("double t_start = MPI_Wtime();"),
        code(""),
        code("// ... алгоритм ..."),
        code(""),
        code("MPI_Barrier(MPI_COMM_WORLD); // чекаємо всіх"),
        code("double t_end = MPI_Wtime();"),
        code("double local_time = t_end - t_start;"),
        code(""),
        code("// Максимальний час = реальний час алгоритму"),
        code("double global_max;"),
        code("MPI_Reduce(&local_time, &global_max, 1, MPI_DOUBLE,"),
        code("           MPI_MAX, 0, MPI_COMM_WORLD);"),
        empty(),
        heading2("BSP (Bulk Synchronous Parallel) модель"),
        body("Структурує паралельні обчислення як послідовність суперкроків: (1) локальні обчислення, (2) глобальна синхронізація (barrier), (3) обмін повідомленнями. Вартість суперкроку: max(local_work_i) + max(comm_i) + sync_cost. Дозволяє передбачати загальний час."),
        empty(),
        heading2("Benchmarks для HPC"),
        bullet("HPL (LINPACK) — розв'язання щільних лінійних систем. Основний benchmark TOP500. Пікова ефективність.", ""),
        bullet("HPCG — розріджені системи, більш реалістичний для реальних задач.", ""),
        bullet("NAS Parallel Benchmarks — набір з 8 задач різного типу (BT, CG, MG, FT, IS, LU, SP, EP).", ""),
        bullet("Intel MPI Benchmarks (IMB) — вимірювання латентності та bandwidth для різних операцій MPI.", ""),
        empty(),
        heading2("Масштабуваність у розподілених системах"),
        body("Для алгоритму Кеннона при N=2000 і p=1,4,16,64: T_calc ~ N³/p (лінійне покращення). T_comm ~ N²/√p × α + N²/p × β (зростає повільніше). При p=64: T_comm стає comparable з T_calc → ефективність знижується. Оптимальна точка p визначається з умови T_calc ≈ T_comm."),
      ]
    },
    {
      id: 47,
      title: "Питання 47. Грід-технології. Поняття спільного віртуального ресурсу",
      content: [
        heading2("Загальний контекст"),
        body("Grid-технології — вищий рівень розподілених обчислень після MPI-кластерів. Якщо MPI з'єднує вузли одного кластеру, Grid з'єднує кластери різних організацій через Інтернет для вирішення задач наукового масштабу."),
        empty(),
        heading2("Що таке Grid?"),
        body("Grid (решітка, за аналогією з електромережею) — інфраструктура для координованого спільного використання обчислювальних ресурсів, баз даних та програм між різними організаціями. Ключова відмінність від хмари: ресурси не орендуються — вони надаються учасниками на умовах взаємності."),
        empty(),
        heading2("Спільний Віртуальний Ресурс (Virtual Organization)"),
        body("Virtual Organization (VO) — динамічна група організацій та осіб, що поділяють ресурси для досягнення спільної мети. Атрибути VO:"),
        bullet("Динамічність: склад змінюється, нові учасники приєднуються/виходять", ""),
        bullet("Distributed control: кожен учасник зберігає контроль над своїми ресурсами і лише делегує доступ", ""),
        bullet("Policy-based: правила доступу, пріоритети, квоти визначаються домовленостями, не централізовано", ""),
        bullet("Goal-oriented: VO існує для конкретної наукової задачі (WLCG для LHC, SETI@home для пошуку ПЦ)", ""),
        empty(),
        heading2("Характеристики Grid"),
        bullet("Гетерогенність: різне обладнання, ОС, batch системи (PBS, SLURM, LSF)", ""),
        bullet("Географічна розподіленість: вузли по всьому світу з Інтернет-з'єднанням", ""),
        bullet("Динамічна доступність: вузли можуть відключатись (вибої, обслуговування)", ""),
        bullet("Масштаб: WLCG обробляє 15 петабайт даних LHC щорічно на ~170 центрах у 42 країнах", ""),
        empty(),
        heading2("Типи Grid"),
        bullet("Computational Grid: обчислювальні ресурси (EGEE, XSEDE, NorduGrid)", ""),
        bullet("Data Grid: зберігання та доступ до великих наборів даних (LCG — LHC Computing Grid)", ""),
        bullet("Desktop Grid / Volunteer Computing: BOINC, Folding@home — ресурси звичайних ПК добровольців", ""),
        bullet("Service Grid: доступ до спеціалізованого обладнання (телескопи, прилади)", ""),
        empty(),
        heading2("Grid vs Cloud vs Cluster"),
        bullet("Cluster: однорідні вузли, один адміністративний домен, MPI, висока продуктивність", ""),
        bullet("Grid: гетерогенні вузли, різні домени, middleware шар, наукова модель", ""),
        bullet("Cloud: централізоване управління, оренда, комерційна модель, elasticity", ""),
      ]
    },
    {
      id: 49,
      title: "Питання 49. Програмне забезпечення грід-технологій",
      content: [
        heading2("Загальний контекст"),
        body("Програмне забезпечення Grid вирішує проблему гетерогенності та розподіленості: як запустити задачу на сотнях різних кластерів у різних організаціях, отримати дані та результати, забезпечити безпеку. Це middleware шар між апаратурою і користувацьким застосунком."),
        empty(),
        heading2("Globus Toolkit"),
        body("Де-факто стандарт Grid middleware. Набір компонентів:"),
        bullet("GRAM (Grid Resource Allocation and Management) — запуск задач на різних batch системах (PBS, SLURM, Condor) через єдиний інтерфейс", ""),
        bullet("GridFTP — ефективна передача файлів: паралельні потоки, відновлення після помилок, третьостороннє копіювання (A → C через B)", ""),
        bullet("GSI (Grid Security Infrastructure) — PKI аутентифікація через X.509 сертифікати, single sign-on", ""),
        bullet("MDS (Monitoring and Discovery System) — LDAP-based реєстр ресурсів та їх стану", ""),
        empty(),
        heading2("GSI: безпека у Grid"),
        body("Проблема: хочемо запустити задачу на 50 сайтах, але не вводити пароль 50 разів. Рішення — проксі-сертифікати:"),
        bullet("Довготривалий сертифікат X.509 (User Certificate) зберігається локально", ""),
        bullet("Короткочасний proxy certificate (12-24 год) делегується серверам", ""),
        bullet("VOMS (Virtual Organization Membership Service) — атрибути членства у VO прикріплюються до proxy", ""),
        bullet("MyProxy Server — зберігання proxy для тривалих задач (коли ноутбук відключений)", ""),
        empty(),
        heading2("BOINC (Berkeley Open Infrastructure for Network Computing)"),
        body("Volunteer computing платформа. Ідея: мільйони ПК добровольців надають обчислення у вільний час."),
        code("// Задача для BOINC може бути на Java або C++"),
        code("// Клієнт завантажує work unit, виконує, повертає результат"),
        code("// Validation: кілька клієнтів виконують одну задачу → голосування"),
        bullet("SETI@home — пошук сигналів позаземного розуму (завершений 2020)", ""),
        bullet("Rosetta@home — згортання білків, допомогло у розробці вакцин COVID-19", ""),
        bullet("Einstein@Home — пошук гравітаційних хвиль та пульсарів", ""),
        bullet("Folding@home — симуляція молекулярної динаміки", ""),
        empty(),
        heading2("Сучасний стан: EGI та інтеграція з Cloud"),
        body("EGI (European Grid Infrastructure) — об'єднує ~300 центрів даних у 50+ країнах, понад 750,000 логічних CPU. XSEDE (США) — об'єднання найбільших HPC центрів для наукових досліджень. Сучасний тренд: гібридні Grid+Cloud середовища. Kubernetes та OpenStack замінюють традиційний Grid middleware. Концепції VO та федеративного управління ресурсами живуть у cloud federation, data spaces, GAIA-X (Європа)."),
        body("Зв'язок з Java: Spring Boot застосунок для матричного множення — це мікросервіс, що може бути розгорнутий на Grid/Cloud вузлі і приймати обчислювальні запити — мікро-реалізація Grid Service."),
      ]
    }
  ];
  
  const doc = new Document({
    numbering: {
      config: [{
        reference: "bullets",
        levels: [{
          level: 0,
          format: LevelFormat.BULLET,
          text: "\u2022",
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } }
        }]
      }]
    },
    styles: {
      default: {
        document: { run: { font: "Arial", size: 22 } }
      },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 28, bold: true, font: "Arial", color: "1F3864" },
          paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 }
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 24, bold: true, font: "Arial", color: "2E5496" },
          paragraph: { spacing: { before: 200, after: 80 }, outlineLevel: 1 }
        }
      ]
    },
    sections: [{
      properties: {
        page: {
          size: { width: 11906, height: 16838 },
          margin: { top: 1440, right: 1080, bottom: 1440, left: 1440 }
        }
      },
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 2000, after: 400 },
          children: [new TextRun({ text: "Технологія паралельних обчислень", bold: true, size: 40, color: "1F3864", font: "Arial" })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
          children: [new TextRun({ text: "Відповіді на питання до екзамену", size: 28, color: "444444", font: "Arial" })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
          children: [new TextRun({ text: "Мова програмування: Java", size: 24, color: "666666", font: "Arial" })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "25 питань · Охоплення всього курсу", size: 22, color: "888888", font: "Arial" })]
        }),
        ...questions.flatMap(q => [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
            children: [new TextRun({ text: q.title, bold: true, size: 28, color: "1F3864", font: "Arial" })]
          }),
          ...q.content
        ])
      ]
    }]
  });
  
  Packer.toBuffer(doc).then(buf => {
    fs.writeFileSync("./docs/uv1.docx", buf);
  });